---
# Install python for Ansible
- name: "install python for Ansible."
  become: yes
  apt:
    name: python3
    state: present

# Install Node.js and npm
- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.8.0 | sudo -E bash -
    sudo apt-get install -y nodejs

# Install PM2
- name: "install PM2."
  become: yes
  npm:
    name: pm2
    global: yes
# VS Code Extension Version: 1.5.0
