---
# Install python for Ansible
- name: "install python for Ansible."
  become: yes
  apt:
    name: python3
    state: present

# Install Node.js and npm
- name: install node
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
    source ~/.bashrc
    nvm install 13.8.0

# Install PM2
- name: "install PM2."
  become: yes
  npm:
    name: pm2
    global: yes
# VS Code Extension Version: 1.5.0
