---
- name: "Make backend directory"
  become: true
  file:
    path: ~/backend
    state: directory

- name: "Copy files to server"
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: "Unzip files as backend folder"
  shell: |
    cd ~/backend
    tar -xzf artifact.tar.gz

- name: "Install dependencies"
  shell: |
    cd ~/backend
    npm install

- name: "Run the app with PM2"
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm -- start

# VS Code Extension Version: 1.5.0
