---
- name: "Make project directory"
  become: yes
  file:
    path: ~/project
    state: directory

- name: "Copy files to server"
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/project

- name: "Unzip files as backend folder"
  shell: |
    cd ~/project
    tar -xzf artifact.tar.gz

- name: "Install dependencies"
  shell: |
    cd ~/project
    npm install

- name: "Run the app with PM2"
  shell: |
    cd ~/project
    pm2 stop default
    pm2 start npm -- start

# VS Code Extension Version: 1.5.0
